CREATE TABLE order(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    endBlock BIGINT NOT NULL,
    isCancelled BOOLEAN NOT NULL,
    isSold BOOLEAN NOT NULL,
    lastBidPrice BIGINT NOT NULL,
    lastBidder VARCHAR(50) NOT NULL,
    orderType INT NOT NULL,
    seller VARCHAR(50) NOT NULL,
    startBlock INT NOT NULL,
    startPrice INT NOT NULL,
    token VARCHAR(50) NOT NULL,
    tokenID VARCHAR(20) REFERENCES product(ID) NOT NULL
)

CREATE TABLE product(
    ID INT NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    attributes REFERENCES normalized_punk_scores(id),
)

CREATE TABLE normalized_punk_scores ( 
    id INT PRIMARY KEY NOT NULL,
    punk_id INT NOT NULL,
    trait_type_0_percentile DOUBLE NOT NULL,
    trait_type_0_rarity DOUBLE NOT NULL,
    trait_type_0_value VARCHAR(30) NOT NULL,
    trait_type_1_percentile DOUBLE NOT NULL, 
    trait_type_1_rarity DOUBLE NOT NULL,
    trait_type_1_value VARCHAR(30) NOT NULL,
    trait_type_2_percentile DOUBLE NOT NULL,
    trait_type_2_rarity DOUBLE NOT NULL,
    trait_type_2_value VARCHAR(30) NOT NULL,
    trait_type_3_percentile DOUBLE NOT NULL,
    trait_type_3_rarity DOUBLE NOT NULL, 
    trait_type_3_value VARCHAR(30) NOT NULL, 
    trait_type_4_percentile DOUBLE NOT NULL, 
    trait_type_4_rarity DOUBLE NOT NULL, 
    trait_type_4_value VARCHAR(30) NOT NULL, 
    trait_type_5_percentile DOUBLE NOT NULL, 
    trait_type_5_rarity DOUBLE NOT NULL, 
    trait_type_5_value VARCHAR(30) NOT NULL, 
    trait_type_6_percentile DOUBLE NOT NULL, 
    trait_type_6_rarity DOUBLE NOT NULL, 
    trait_type_6_value VARCHAR(30) NOT NULL, 
    trait_type_7_percentile DOUBLE NOT NULL, 
    trait_type_7_rarity DOUBLE NOT NULL, 
    trait_type_7_value VARCHAR(30) NOT NULL, 
    trait_type_8_percentile DOUBLE NOT NULL, 
    trait_type_8_rarity DOUBLE NOT NULL, 
    trait_type_8_value VARCHAR(30) NOT NULL, 
    trait_type_9_percentile DOUBLE NOT NULL, 
    trait_type_9_rarity DOUBLE NOT NULL, 
    trait_type_9_value VARCHAR(30) NOT NULL, 
    trait_type_10_percentile DOUBLE NOT NULL, 
    trait_type_10_rarity DOUBLE NOT NULL, 
    trait_type_10_value VARCHAR(30) NOT NULL, 
    trait_type_11_percentile DOUBLE NOT NULL, 
    trait_type_11_rarity DOUBLE NOT NULL, 
    trait_type_11_value VARCHAR(30) NOT NULL, 
    trait_count INT NOT NULL,  
    trait_count_percentile DOUBLE NOT NULL, 
    trait_count_rarity DOUBLE NOT NULL, 
    rarity_sum DOUBLE NOT NULL, 
    rarity_rank INT)